# Generated by Django 4.0.6 on 2022-09-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.paymenttype'),
            preserve_default=False,
        ),
    ]
