# Generated by Django 4.0.6 on 2022-09-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
